In [4]:
# Importing necessary libraries
import pandas as pd

data = pd.read_csv('messy_population_data.csv')

# Display basic information about the dataset
print("Basic Information:")
print(data.info())

# Descriptive Stats:
print("\nDescriptive Statistics:")
print(data.describe())

# Missing values in each columns:
print("\nMissing Values:")
missing_values = data.isnull().sum()
print(missing_values)

# Duplicate rows: 
print("\nDuplicate Rows:")
duplicate_rows = data.duplicated().sum()
print(f'Total duplicate rows: {duplicate_rows}')

# Display the number of unique values in each column
print("\nUnique Values per Column:")
unique_values = data.nunique()
print(unique_values)

print("\nValue Counts for 'income_groups':")
print(data['income_groups'].value_counts())

print("\nValue Counts for 'gender':")
print(data['gender'].value_counts())

print("\nYear Value Counts:")
print(data['year'].value_counts().sort_index())

print("\nPopulation Value Counts:")
print(data['population'].value_counts().sort_index())

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125718 entries, 0 to 125717
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   income_groups  119412 non-null  object
 1   age            119495 non-null  float64
 2   gender         119811 non-null  float64
 3   year           119516 non-null  float64
 4   population     119378 non-null  float64
dtypes: float64(4), object(1)
memory usage: 4.8+ MB
None

Descriptive Statistics:
                 age         gender           year    population
count  119495.000000  119811.000000  119516.000000  1.193780e+05
mean       50.007038       1.578578    2025.068049  1.112983e+08
std        29.154144       0.590559      43.584951  1.265205e+09
min         0.000000       1.000000    1950.000000  2.100000e+01
25%        25.000000       1.000000    1987.000000  2.316023e+06
50%        50.000000       2.000000    2025.000000  7.145754e+06
75%        75.000000       2.000000    2063.000000  1.466388e+07
max       100.000000       3.000000    2119.000000  3.293043e+10

Missing Values:
income_groups    6306
age              6223
gender           5907
year             6202
population       6340
dtype: int64

Duplicate Rows:
Total duplicate rows: 2950

Unique Values per Column:
income_groups         8
age                 101
gender                3
year                169
population       114925
dtype: int64

Value Counts for 'income_groups':
income_groups
low_income                  28433
upper_middle_income         28354
high_income                 28343
lower_middle_income         28323
lower_middle_income_typo     1517
low_income_typo              1505
high_income_typo             1475
upper_middle_income_typo     1462
Name: count, dtype: int64

Value Counts for 'gender':
gender
1.0    56777
2.0    56748
3.0     6286
Name: count, dtype: int64

Year Value Counts:
year
1950.0    788
1951.0    782
1952.0    787
1953.0    780
1954.0    797
         ...
2115.0      3
2116.0      2
2117.0      1
2118.0      1
2119.0      3
Name: count, Length: 169, dtype: int64

Population Value Counts:
population
2.100000e+01    2
2.200000e+01    1
2.400000e+01    1
2.500000e+01    1
2.800000e+01    2
               ..
3.231194e+10    1
3.233189e+10    1
3.251144e+10    1
3.263962e+10    1
3.293043e+10    1
Name: count, Length: 114925, dtype: int64

In [25]:
#eda or cleaned:
data2= pd.read_csv('cleaned_population_data.csv')

# Display the number of rows and columns
print("Rows:", data2.shape[0])
print("Columns:", data2.shape[1])

info = data2.info() 
description = data2.describe()  

unique_values = data2.nunique()
print(unique_values)

print(data2.describe())

Rows: 56705
Columns: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56705 entries, 0 to 56704
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   income_groups  56705 non-null  object
 1   age            56705 non-null  float64
 2   gender         56705 non-null  float64
 3   year           56705 non-null  int64
 4   population     56705 non-null  int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.2+ MB
income_groups        8
age                101
gender               3
year                76
population       52887
dtype: int64
                age        gender         year    population
count  56705.000000  56705.000000  56705.00000  5.670500e+04
mean      50.178803      1.580831   1799.73602  6.234318e+06
std       28.428350      0.591509    581.10287  7.145505e+06
min        0.000000      1.000000     -1.00000  0.000000e+00
25%       26.000000      1.000000   1962.00000  5.740910e+05
50%       50.000000      2.000000   1983.00000  4.042743e+06
75%       74.000000      2.000000   2004.00000  8.159160e+06
max      100.000000      3.000000   2024.00000  3.263864e+07